### ISSUE TITLE
[bug] Mining abort

### ISSUE THREAD

**Issue by dduo518** [NoteProtocol/NoteWallet#6]
Mining interruption

os : windows 11
node version: v20.11.1
nodemon version: [nodemon] 3.0.3

```shell
checking 0ea408861b23ac91b6eebfd5b06e115746797bf5a43e55c0ea1c34a91a513769 115906
checking 7a44435f842605ab7f3cab35b45681cdd5ce71cd461b67f168ad58cff473da0b 115907
checking ee36f1d2c3d80f78ca4bf0bd054bbaededf72765d193c732088579deaf16fcbd 115908
checking 25c8164b0f6d63ea3e4fdf65c8c883c759c05fd77941167c076d18f2acf863d1 115909
checking 6ce7faab6695b3f47ceaf755383641abc1769200e6dfc3c86c565f0892cfb634 115910
checking 186a6e59ada7c8b2f2c3a992766d488bc6e1b5dfd25747994f8a66cf805dda94 115911
checking 5c1dd98fa8bf1675522879b76b130b7256a30061e5d1f12dc386b99b9fbb47d3 115912
checking 6ce18840a5c4aded126105b6ae8b488f93b12c41f1e26cc148680e01bfc6bff7 115913
checking 8d656a80db7a522d0ca8be47125cb058a7eda24d2dde242aef2b59d9f635355f 115914
checking 3230d166955ce64235c83ff212df7284669082e0432eef5f90113c230dcfbc87 115915
🚀 ~ mintPowToken ~ verifyResult: { success: true, error: '' } {
  toAddress: 'bc1phd6rsq5744fpwc98ezl55e2vl342rtdlh89kf64rgkknxeszd9wqp8k0hr',
  noteUtxo: {
    address: 'bc1phd6rsq5744fpwc98ezl55e2vl342rtdlh89kf64rgkknxeszd9wqp8k0hr',
    txId: 'e3e08a92d9399dbc29949646c8c3c71a8304e4c6038db34eadf9bed967169e10',
    outputIndex: 0,
    height: 831574,
    script: '5120bb7438029ead521760a7c8bf4a654cfc6aa1adbfb9cb64eaa345ad336602695c',
    satoshis: 546,
    type: 'P2TR-NOTE',
    time: 1708628271
  },
  payUtxos: [
    {
      address: 'bc1q2k7z56lx5ylquzzq58qmzyw8mlq32tq9wek4yr',
      txId: 'e3e08a92d9399dbc29949646c8c3c71a8304e4c6038db34eadf9bed967169e10',
      outputIndex: 1,
      height: 831574,
      script: '001455bc2a6be6a13e0e0840a1c1b111c7dfc1152c05',
      satoshis: 44239,
      type: 'P2WPKH',
      time: 1708628271
    }
  ],
  txId: 'b6755e3200854910084d4a3cd6165867b00710790ff690251adfd4a967c29b48',
  txHex: '02000000000102109e1667d9bef9ad4eb38d03c6e404831ac7c3c846969429bc9d39d9928ae0e30000000000ffffffff109e1667d9bef9ad4eb38d03c6e404831ac7c3c846969429bc9d39d9928ae0e30100000000ffffffff022202000000000000225120bb7438029ead521760a7c8bf4a654cfc6aa1adbfb9cb64eaa345ad336602695c469e00000000000016001455bc2a6be6a13e0e0840a1c1b111c7dfc1152c050840e6e1b0ecb1b92fa4e9ae8712eb1b0fdd460c08ebe5734c998852f928db4dfda140c9d6cc8214bf05d39f5c6ea9bf891421105bf6a8dce931c1675c6173d73cbc2684a3616d74cf000000174876e800a26f70a46d696e74a170a36e3230a47469636ba44e4f5445000000002a044e4f54456d6d6d20d42a45127173f9a5dbd45a0830c5e9c3c3c960edd5790cfc6a8e8f57ce84a654ac41c0d42a45127173f9a5dbd45a0830c5e9c3c3c960edd5790cfc6a8e8f57ce84a6547f609ead781d87d50e665a67d826b5b4823f4fbae61c1922dfd0e9ca1ba7d6430247304402205cc9e821d0bbd16c1c49bad78fdf6d22b77b705e84e5fdf7d458796348ff396e02207bcf488a876c35e13bc92c271d3e73364ad30f598a614a80c3c97313bcfd8546012102d42a45127173f9a5dbd45a0830c5e9c3c3c960edd5790cfc6a8e8f57ce84a654cbc40100',
  feeRate: 15000
}
{
  success: false,
  errror: {
    code: 400,
    message: 'VerifyError: SCRIPT_ERR_EVAL_FALSE_IN_STACK, fails at OP_ENDIF\n'
  }
}
```

**Comment by dduo518** [comment]
os:macOS monterey 12.7.1 (21G920)
node version :node v21.6.2
[nodemon] 3.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts




checking b79207f29032075122100578d9f3082187e1fa80e77e7eccae7fca0c955bb87b 165997
checking 0b5a80f20e68060b50a5f1e2a9af6f255fcf2da945f6f15eee1d4276a1002b34 165998
checking 3230481b1c2b8ac0bba34956ea764e17d8ede53550e59d01a2e8d7304338f30f 165999
🚀 ~ mintPowToken ~ verifyResult: { success: true, error: '' } {
  toAddress: 'bc1pfh5rhdf74zygw96zxzqaj9ns9hvd7348e5prgysundvv2445qxls9z024y',
  noteUtxo: {
    address: 'bc1pfh5rhdf74zygw96zxzqaj9ns9hvd7348e5prgysundvv2445qxls9z024y',
    txId: '4740cbb562612c242540223feef53df8a8b18c923690ecba2bc38b314f140b26',
    outputIndex: 0,
    height: null,
    script: '51204de83bb53ea8888717423081d916702dd8df46a7cd0234121c9b58c556b401bf',
    satoshis: 546,
    type: 'P2TR-NOTE',
    time: 1708626002
  },
  payUtxos: [
    {
      address: 'bc1qrga6u62ta0c4hs6305zlrw78p3v5rz000heus5',
      txId: '4740cbb562612c242540223feef53df8a8b18c923690ecba2bc38b314f140b26',
      outputIndex: 1,
      height: null,
      script: '00141a3bae694bebf15bc3517d05f1bbc70c594189ef',
      satoshis: 46852,
      type: 'P2WPKH',
      time: 1708626002
    }
  ],
  txId: 'fed7eb71167f2f5b75f83571e5fc376b4f6db237826bd109032823a95dcef252',
  txHex: '02000000000102260b144f318bc32bbaec9036928cb1a8f83df5ee3f224025242c6162b5cb40470000000000ffffffff260b144f318bc32bbaec9036928cb1a8f83df5ee3f224025242c6162b5cb40470100000000ffffffff0222020000000000002251204de83bb53ea8888717423081d916702dd8df46a7cd0234121c9b58c556b401bf8ba60000000000001600141a3bae694bebf15bc3517d05f1bbc70c594189ef08403ceca7667509ade9a693f55f720f6abf51bc38f34c142e1e30284fb102410955dda01305b41325dcadde816645967a92928dc0607dfc574a79273c21eef9d8622684a3616d74cf000000174876e800a26f70a46d696e74a170a36e3230a47469636ba44e4f5445000000002a044e4f54456d6d6d2044df4d1a68131083d617943287106e2def89c48f61a2a86cda2fc57d6fb97ecaac41c044df4d1a68131083d617943287106e2def89c48f61a2a86cda2fc57d6fb97eca553f28fceef52cc754f50e09704e62bc495ddb1312fe3ebe5a914c9725bb86a00247304402201fb2c4f9d68d102e77dc970449f739ea43b66e4d112d6c55be6a22e1c4916ba202202e2e853dda0b28fae27ffdaa5d98ae697da2cdc634f83d8836733036155a459201210244df4d1a68131083d617943287106e2def89c48f61a2a86cda2fc57d6fb97eca6f880200',
  feeRate: 17000
}
bin.js mintnote

Mint Note Token

选项：
  --help     显示帮助信息                                                 [布尔]
  --version  显示版本号                                                   [布尔]

Error: write EPIPE
    at _parseError (/Users/z_chong/Desktop/NoteWallet/src/urchain.ts:34:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Urchain.broadcast (/Users/z_chong/Desktop/NoteWallet/src/urchain.ts:159:12)
    at async BTCWallet.broadcastTransaction (/Users/z_chong/Desktop/NoteWallet/src/wallet.ts:110:12)
    at async mintPowToken (/Users/z_chong/Desktop/NoteWallet/src/mint.ts:84:18)
    at async Object.handler (/Users/z_chong/Desktop/NoteWallet/src/command-line.ts:165:26)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dduo518** [comment]
Mining interruption

os : windows 11
node version: v20.11.1
nodemon version: [nodemon] 3.0.3

checking 7aaecdf2c544c5906ee15ba3fa8555c7f2bd6fa3f88ca838cedcd1a647ce7d12 23434
checking 240c2c601c4ddf57e92cd656414dc61ea76b2e60cb00998d082f9363b7260585 23435
checking c4eca496089d87e6e8938c82dd14c63ddeab1ee16cb6e2c45c42222513147e16 23436
checking 0dbd1fcf2ec8cd0f0f48a066c5ac7c3e4141fbd551dc7dce2ae08968e60729e0 23437
checking a034e5e616441ee9f765681b359ab499f5d9b23bb0674f1556276466fac9165c 23438
checking 3230874893bed3a9d8783914e986d1c761b81f55a3d946d53f87a7b103b5ac65 23439
🚀 ~ mintPowToken ~ verifyResult: { success: true, error: '' } {
  toAddress: 'bc1phd6rsq5744fpwc98ezl55e2vl342rtdlh89kf64rgkknxeszd9wqp8k0hr',
  noteUtxo: {
    address: 'bc1phd6rsq5744fpwc98ezl55e2vl342rtdlh89kf64rgkknxeszd9wqp8k0hr',
    txId: 'e3e08a92d9399dbc29949646c8c3c71a8304e4c6038db34eadf9bed967169e10',
    outputIndex: 0,
    height: 831574,
    script: '5120bb7438029ead521760a7c8bf4a654cfc6aa1adbfb9cb64eaa345ad336602695c',
    satoshis: 546,
    type: 'P2TR-NOTE',
    time: 1708628271
  },
  payUtxos: [
    {
      address: 'bc1q2k7z56lx5ylquzzq58qmzyw8mlq32tq9wek4yr',
      txId: 'e3e08a92d9399dbc29949646c8c3c71a8304e4c6038db34eadf9bed967169e10',
      outputIndex: 1,
      height: 831574,
      script: '001455bc2a6be6a13e0e0840a1c1b111c7dfc1152c05',
      satoshis: 44239,
      type: 'P2WPKH',
      time: 1708628271
    }
  ],
  txId: '2ece012bb414ee75c8241e4b5c03978e9d0f2d7b66fec7c29f2f2f1216f247dc',
  txHex: '02000000000102109e1667d9bef9ad4eb38d03c6e404831ac7c3c846969429bc9d39d9928ae0e30000000000ffffffff109e1667d9bef9ad4eb38d03c6e404831ac7c3c846969429bc9d39d9928ae0e30100000000ffffffff022202000000000000225120bb7438029ead521760a7c8bf4a654cfc6aa1adbfb9cb64eaa345ad336602695c36a000000000000016001455bc2a6be6a13e0e0840a1c1b111c7dfc1152c05084022f97ba5e70d6223fdc1211b6a74f4c2a558cd55f6c792d11149a86a9e99b03e4fb666757a6282c8c3e2561ada99699deeefe6874ad9edcd0195af96312ca0112684a3616d74cf000000174876e800a26f70a46d696e74a170a36e3230a47469636ba44e4f5445000000002a044e4f54456d6d6d20d42a45127173f9a5dbd45a0830c5e9c3c3c960edd5790cfc6a8e8f57ce84a654ac41c0d42a45127173f9a5dbd45a0830c5e9c3c3c960edd5790cfc6a8e8f57ce84a6547f609ead781d87d50e665a67d826b5b4823f4fbae61c1922dfd0e9ca1ba7d64302483045022100cc6da0c6a0ee88a4575c933c9dbbc69f1418f3455e0297fbf8d4a055844874dc02203e50d3aa138d48d0ee447620c2c954c511babc2316e8adde83efdc2f30a31baa012102d42a45127173f9a5dbd45a0830c5e9c3c3c960edd5790cfc6a8e8f57ce84a6548f5b0000',
  feeRate: 13000
}
{
  success: false,
  errror: {
    code: 400,
    message: 'VerifyError: SCRIPT_ERR_EVAL_FALSE_IN_STACK, fails at OP_ENDIF\n'
  }
}

**Comment by LudovicPaguet** [comment]
> os:macOS monterey 12.7.1 (21G920) node version :node v21.6.2 [nodemon] 3.0.3 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): src/**/* [nodemon] watching extensions: ts
> 
> checking b79207f29032075122100578d9f3082187e1fa80e77e7eccae7fca0c955bb87b 165997 checking 0b5a80f20e68060b50a5f1e2a9af6f255fcf2da945f6f15eee1d4276a1002b34 165998 checking 3230481b1c2b8ac0bba34956ea764e17d8ede53550e59d01a2e8d7304338f30f 165999 🚀 ~ mintPowToken ~ verifyResult: { success: true, error: '' } { toAddress: 'bc1pfh5rhdf74zygw96zxzqaj9ns9hvd7348e5prgysundvv2445qxls9z024y', noteUtxo: { address: 'bc1pfh5rhdf74zygw96zxzqaj9ns9hvd7348e5prgysundvv2445qxls9z024y', txId: '4740cbb562612c242540223feef53df8a8b18c923690ecba2bc38b314f140b26', outputIndex: 0, height: null, script: '51204de83bb53ea8888717423081d916702dd8df46a7cd0234121c9b58c556b401bf', satoshis: 546, type: 'P2TR-NOTE', time: 1708626002 }, payUtxos: [ { address: 'bc1qrga6u62ta0c4hs6305zlrw78p3v5rz000heus5', txId: '4740cbb562612c242540223feef53df8a8b18c923690ecba2bc38b314f140b26', outputIndex: 1, height: null, script: '00141a3bae694bebf15bc3517d05f1bbc70c594189ef', satoshis: 46852, type: 'P2WPKH', time: 1708626002 } ], txId: 'fed7eb71167f2f5b75f83571e5fc376b4f6db237826bd109032823a95dcef252', txHex: '02000000000102260b144f318bc32bbaec9036928cb1a8f83df5ee3f224025242c6162b5cb40470000000000ffffffff260b144f318bc32bbaec9036928cb1a8f83df5ee3f224025242c6162b5cb40470100000000ffffffff0222020000000000002251204de83bb53ea8888717423081d916702dd8df46a7cd0234121c9b58c556b401bf8ba60000000000001600141a3bae694bebf15bc3517d05f1bbc70c594189ef08403ceca7667509ade9a693f55f720f6abf51bc38f34c142e1e30284fb102410955dda01305b41325dcadde816645967a92928dc0607dfc574a79273c21eef9d8622684a3616d74cf000000174876e800a26f70a46d696e74a170a36e3230a47469636ba44e4f5445000000002a044e4f54456d6d6d2044df4d1a68131083d617943287106e2def89c48f61a2a86cda2fc57d6fb97ecaac41c044df4d1a68131083d617943287106e2def89c48f61a2a86cda2fc57d6fb97eca553f28fceef52cc754f50e09704e62bc495ddb1312fe3ebe5a914c9725bb86a00247304402201fb2c4f9d68d102e77dc970449f739ea43b66e4d112d6c55be6a22e1c4916ba202202e2e853dda0b28fae27ffdaa5d98ae697da2cdc634f83d8836733036155a459201210244df4d1a68131083d617943287106e2def89c48f61a2a86cda2fc57d6fb97eca6f880200', feeRate: 17000 } bin.js mintnote
> 
> Mint Note Token
> 
> 选项： --help 显示帮助信息 [布尔] --version 显示版本号 [布尔]
> 
> Error: write EPIPE at _parseError (/Users/z_chong/Desktop/NoteWallet/src/urchain.ts:34:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at async Urchain.broadcast (/Users/z_chong/Desktop/NoteWallet/src/urchain.ts:159:12) at async BTCWallet.broadcastTransaction (/Users/z_chong/Desktop/NoteWallet/src/wallet.ts:110:12) at async mintPowToken (/Users/z_chong/Desktop/NoteWallet/src/mint.ts:84:18) at async Object.handler (/Users/z_chong/Desktop/NoteWallet/src/command-line.ts:165:26) [nodemon] app crashed - waiting for file changes before starting...

Same Issue on Ubuntu

**Comment by time0x** [comment]
减半了，就不给你广播了
