### ISSUE TITLE
unconfirmed 记录对应 tx 未上链，导致无法确认及 mint

### ISSUE THREAD

**Issue by xughv** [NoteProtocol/NoteWallet#7]
mainAddress: 'bc1qhqz9mqhysylzwyft9ur4ctw0zlwhlw5cuy0ddy'
tokenAddress: 'bc1p0n6luq4k6q6ngjckwlv8rehhdrv65qjpm8lxkhht56yjc7hhxygs7yg4ys'

<img width="191" alt="image" src="https://github.com/NoteProtocol/NoteWallet/assets/14882240/3e160a66-8944-4c45-88c0-04a062a157e1">

成功提交，生成 unconfirmed 记录，但实际 tx 未上链，导致无法确认，后续 mint 也无法提交

**Comment by chuzi681** [comment]
哥们是怎么解决的，我看你的地址在发单了

> mainAddress: 'bc1qenhhhhj2m0asvjv43zd32e002kgh8lddvkgrmr' tokenAddress: 'bc1p7dyqe7hlpv93gmm3hfe575uds6fktwnp8yf9rpggrk659n8es2tqzr68tq'
> 
> 成功提交，生成 unconfirmed 记录，但实际 tx 未上链，导致无法确认，后续 mint 也无法提交

**Comment by xughv** [comment]
> 哥们是怎么解决的，我看你的地址在发单了
> 
> > mainAddress: 'bc1qenhhhhj2m0asvjv43zd32e002kgh8lddvkgrmr' tokenAddress: 'bc1p7dyqe7hlpv93gmm3hfe575uds6fktwnp8yf9rpggrk659n8es2tqzr68tq'
> > 成功提交，生成 unconfirmed 记录，但实际 tx 未上链，导致无法确认，后续 mint 也无法提交

我发现我贴错钱包地址了，我改一下，哈哈哈，解决方法就再开几个新的钱包

**Comment by chuzi681** [comment]
啊，换新钱包就能解决的？

**Comment by chuzi681** [comment]
我的是显示交易id但是不进内存池，咱们是同一个问题吗

**Comment by xughv** [comment]
> 我的是显示交易id但是不进内存池，咱们是同一个问题吗

可能不是，你这个是该改减半的数量了吧 ..

我现在遇到是有一笔挖到的确认不了

<img width="191" alt="image" src="https://github.com/NoteProtocol/NoteWallet/assets/14882240/d3c7aac8-374c-4f79-8025-2a838623b850">

**Comment by sfhacker** [comment]
Embarrassing!
